import mysql.connector
from mysql.connector import errorcode

print("Conectando...")
try:
      conn = mysql.connector.connect(
            host='127.0.0.1',
            user='root',
            password=''
      )
except mysql.connector.Error as err:
      if err.errno == errorcode.ER_ACCESS_DENIED_ERROR:
            print('Existe algo errado no nome de usuário ou senha')
      else:
            print(err)

cursor = conn.cursor()

cursor.execute("DROP DATABASE IF EXISTS `saquabus`;")

cursor.execute("CREATE DATABASE `saquabus`;")

cursor.execute("USE `saquabus`;")

# criando tabelas
TABLES = {}
TABLES['Lines'] = ('''
      CREATE TABLE `bus_lines` (
      `id` int(11) NOT NULL AUTO_INCREMENT,
      `hour` time NOT NULL,
      `origin` varchar(255) NOT NULL,
      `destination` varchar(255) NOT NULL,
      `line` varchar(50) NOT NULL,
      `is_saturday` BOOLEAN NOT NULL DEFAULT FALSE,
      `is_sunday_or_holiday` BOOLEAN NOT NULL DEFAULT FALSE,
      `obs` varchar(255) NULL,
      PRIMARY KEY (`id`)
      ) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci;''')

for tabela_nome in TABLES:
      tabela_sql = TABLES[tabela_nome]
      try:
            print('Criando tabela {}:'.format(tabela_nome), end=' ')
            cursor.execute(tabela_sql)
      except mysql.connector.Error as err:
            if err.errno == errorcode.ER_TABLE_EXISTS_ERROR:
                  print('Já existe')
            else:
                  print(err.msg)
      else:
            print('OK')


# inserindo dados
lines_sql = 'INSERT INTO bus_lines (hour, origin, destination, line, obs, is_saturday, is_sunday_or_holiday) VALUES (%s, %s, %s, %s, %s, %s, %s)'
lines = [
    ('05:20', 'BACAXÁ', 'VILATUR', 'LINHA 42 ROD. AMARAL PEIXOTO', 'ROD. AMARAL PEIXOTO PRÓXIMO AO PONTO MONTES BRANCOS, BONSUCESSO E VILATUR', False, False),
    ('05:40', 'BACAXÁ', 'VILATUR', 'LINHA 23 ÁGUA BRANCA', 'TERMINAL BACAXÁ, CAIXA D´ÁGUA, ÁGUA BRANCA, MANGUEIRAS, CAJUEIRO E VILATUR.', False, False),
    ('06:00', 'BACAXÁ', 'VILATUR', 'LINHA 23 ÁGUA BRANCA', 'TERMINAL BACAXÁ, CAIXA D´ÁGUA, ÁGUA BRANCA, MANGUEIRAS, CAJUEIRO E VILATUR.', False, False),
    ('06:40', 'BACAXÁ', 'VILATUR', 'LINHA 23 ÁGUA BRANCA', 'TERMINAL BACAXÁ, CAIXA D´ÁGUA, ÁGUA BRANCA, MANGUEIRAS, CAJUEIRO E VILATUR.', False, False),
    ('07:00', 'BACAXÁ', 'VILATUR', 'LINHA 42 ROD. AMARAL PEIXOTO', 'ROD. AMARAL PEIXOTO PRÓXIMO AO PONTO MONTES BRANCOS, BONSUCESSO E VILATUR', False, False),
    ('07:20', 'BACAXÁ', 'VILATUR', 'LINHA 23 ÁGUA BRANCA', 'TERMINAL BACAXÁ, CAIXA D´ÁGUA, ÁGUA BRANCA, MANGUEIRAS, CAJUEIRO E VILATUR.', False, False),
    ('08:00', 'BACAXÁ', 'VILATUR', 'LINHA 23 ÁGUA BRANCA', 'TERMINAL BACAXÁ, CAIXA D´ÁGUA, ÁGUA BRANCA, MANGUEIRAS, CAJUEIRO E VILATUR.', False, False),
    ('08:40', 'BACAXÁ', 'VILATUR', 'LINHA 23 ÁGUA BRANCA', 'TERMINAL BACAXÁ, CAIXA D´ÁGUA, ÁGUA BRANCA, MANGUEIRAS, CAJUEIRO E VILATUR.', False, False),
    ('09:20', 'BACAXÁ', 'VILATUR', 'LINHA 23 ÁGUA BRANCA', 'TERMINAL BACAXÁ, CAIXA D´ÁGUA, ÁGUA BRANCA, MANGUEIRAS, CAJUEIRO E VILATUR.', False, False),
    ('10:00', 'BACAXÁ', 'VILATUR', 'LINHA 23 ÁGUA BRANCA', 'TERMINAL BACAXÁ, CAIXA D´ÁGUA, ÁGUA BRANCA, MANGUEIRAS, CAJUEIRO E VILATUR.', False, False),
    ('10:40', 'BACAXÁ', 'VILATUR', 'LINHA 23 ÁGUA BRANCA', 'TERMINAL BACAXÁ, CAIXA D´ÁGUA, ÁGUA BRANCA, MANGUEIRAS, CAJUEIRO E VILATUR.', False, False),
    ('11:20', 'BACAXÁ', 'VILATUR', 'LINHA 23 ÁGUA BRANCA', 'TERMINAL BACAXÁ, CAIXA D´ÁGUA, ÁGUA BRANCA, MANGUEIRAS, CAJUEIRO E VILATUR.', False, False),
    ('12:00', 'BACAXÁ', 'VILATUR', 'LINHA 23 ÁGUA BRANCA', 'TERMINAL BACAXÁ, CAIXA D´ÁGUA, ÁGUA BRANCA, MANGUEIRAS, CAJUEIRO E VILATUR.', False, False),
    ('12:20', 'BACAXÁ', 'VILATUR', 'LINHA 42 ROD. AMARAL PEIXOTO', 'ROD. AMARAL PEIXOTO PRÓXIMO AO PONTO MONTES BRANCOS, BONSUCESSO E VILATUR', False, False),
    ('12:40', 'BACAXÁ', 'VILATUR', 'LINHA 23 ÁGUA BRANCA', 'TERMINAL BACAXÁ, CAIXA D´ÁGUA, ÁGUA BRANCA, MANGUEIRAS, CAJUEIRO E VILATUR.', False, False),
    ('13:20', 'BACAXÁ', 'VILATUR', 'LINHA 23 ÁGUA BRANCA', 'TERMINAL BACAXÁ, CAIXA D´ÁGUA, ÁGUA BRANCA, MANGUEIRAS, CAJUEIRO E VILATUR.', False, False),
    ('14:00', 'BACAXÁ', 'VILATUR', 'LINHA 23 ÁGUA BRANCA', 'TERMINAL BACAXÁ, CAIXA D´ÁGUA, ÁGUA BRANCA, MANGUEIRAS, CAJUEIRO E VILATUR.', False, False),
    ('14:40', 'BACAXÁ', 'VILATUR', 'LINHA 23 ÁGUA BRANCA', 'TERMINAL BACAXÁ, CAIXA D´ÁGUA, ÁGUA BRANCA, MANGUEIRAS, CAJUEIRO E VILATUR.', False, False),
    ('15:20', 'BACAXÁ', 'VILATUR', 'LINHA 23 ÁGUA BRANCA', 'TERMINAL BACAXÁ, CAIXA D´ÁGUA, ÁGUA BRANCA, MANGUEIRAS, CAJUEIRO E VILATUR.', False, False),
    ('16:00', 'BACAXÁ', 'VILATUR', 'LINHA 23 ÁGUA BRANCA', 'TERMINAL BACAXÁ, CAIXA D´ÁGUA, ÁGUA BRANCA, MANGUEIRAS, CAJUEIRO E VILATUR.', False, False),
    ('16:40', 'BACAXÁ', 'VILATUR', 'LINHA 23 ÁGUA BRANCA', 'TERMINAL BACAXÁ, CAIXA D´ÁGUA, ÁGUA BRANCA, MANGUEIRAS, CAJUEIRO E VILATUR.', False, False),
    ('17:00', 'BACAXÁ', 'VILATUR', 'LINHA 42 ROD. AMARAL PEIXOTO', 'ROD. AMARAL PEIXOTO PRÓXIMO AO PONTO MONTES BRANCOS, BONSUCESSO E VILATUR', False, False),
    ('17:20', 'BACAXÁ', 'VILATUR', 'LINHA 23 ÁGUA BRANCA', 'TERMINAL BACAXÁ, CAIXA D´ÁGUA, ÁGUA BRANCA, MANGUEIRAS, CAJUEIRO E VILATUR.', False, False),
    ('18:00', 'BACAXÁ', 'VILATUR', 'LINHA 23 ÁGUA BRANCA', 'TERMINAL BACAXÁ, CAIXA D´ÁGUA, ÁGUA BRANCA, MANGUEIRAS, CAJUEIRO E VILATUR.', False, False),
    ('18:20', 'BACAXÁ', 'VILATUR', 'LINHA 42 ROD. AMARAL PEIXOTO', 'ROD. AMARAL PEIXOTO PRÓXIMO AO PONTO MONTES BRANCOS, BONSUCESSO E VILATUR', False, False),
    ('19:00', 'BACAXÁ', 'VILATUR', 'LINHA 23 ÁGUA BRANCA', 'TERMINAL BACAXÁ, CAIXA D´ÁGUA, ÁGUA BRANCA, MANGUEIRAS, CAJUEIRO E VILATUR.', False, False),
    ('20:20', 'BACAXÁ', 'VILATUR', 'LINHA 23 ÁGUA BRANCA', 'TERMINAL BACAXÁ, CAIXA D´ÁGUA, ÁGUA BRANCA, MANGUEIRAS, CAJUEIRO E VILATUR.', False, False),
    ('21:30', 'BACAXÁ', 'VILATUR', 'LINHA 23 ÁGUA BRANCA', 'TERMINAL BACAXÁ, CAIXA D´ÁGUA, ÁGUA BRANCA, MANGUEIRAS, CAJUEIRO E VILATUR.', False, False),
    ('06:00', 'VILATUR', 'BACAXÁ', 'LINHA 42 ROD. AMARAL PEIXOTO', 'ROD. AMARAL PEIXOTO PRÓXIMO AO PONTO MONTES BRANCOS, BONSUCESSO E VILATUR', False, False),
    ('06:20', 'VILATUR', 'BACAXÁ', 'LINHA 23 ÁGUA BRANCA', 'TERMINAL BACAXÁ, CAIXA D´ÁGUA, ÁGUA BRANCA, MANGUEIRAS, CAJUEIRO E VILATUR.', False, False),
    ('06:40', 'VILATUR', 'BACAXÁ', 'LINHA 23 ÁGUA BRANCA', 'TERMINAL BACAXÁ, CAIXA D´ÁGUA, ÁGUA BRANCA, MANGUEIRAS, CAJUEIRO E VILATUR.', False, False),
    ('07:15', 'VILATUR', 'BACAXÁ', 'LINHA 23 ÁGUA BRANCA', 'TERMINAL BACAXÁ, CAIXA D´ÁGUA, ÁGUA BRANCA, MANGUEIRAS, CAJUEIRO E VILATUR.', False, False),
    ('07:35', 'VILATUR', 'BACAXÁ', 'LINHA 42 ROD. AMARAL PEIXOTO', 'ROD. AMARAL PEIXOTO PRÓXIMO AO PONTO MONTES BRANCOS, BONSUCESSO E VILATUR', False, False),
    ('07:55', 'VILATUR', 'BACAXÁ', 'LINHA 23 ÁGUA BRANCA', 'TERMINAL BACAXÁ, CAIXA D´ÁGUA, ÁGUA BRANCA, MANGUEIRAS, CAJUEIRO E VILATUR.', False, False),
    ('08:35', 'VILATUR', 'BACAXÁ', 'LINHA 23 ÁGUA BRANCA', 'TERMINAL BACAXÁ, CAIXA D´ÁGUA, ÁGUA BRANCA, MANGUEIRAS, CAJUEIRO E VILATUR.', False, False),
    ('09:15', 'VILATUR', 'BACAXÁ', 'LINHA 23 ÁGUA BRANCA', 'TERMINAL BACAXÁ, CAIXA D´ÁGUA, ÁGUA BRANCA, MANGUEIRAS, CAJUEIRO E VILATUR.', False, False),
    ('09:55', 'VILATUR', 'BACAXÁ', 'LINHA 23 ÁGUA BRANCA', 'TERMINAL BACAXÁ, CAIXA D´ÁGUA, ÁGUA BRANCA, MANGUEIRAS, CAJUEIRO E VILATUR.', False, False),
    ('10:35', 'VILATUR', 'BACAXÁ', 'LINHA 23 ÁGUA BRANCA', 'TERMINAL BACAXÁ, CAIXA D´ÁGUA, ÁGUA BRANCA, MANGUEIRAS, CAJUEIRO E VILATUR.', False, False),
    ('11:15', 'VILATUR', 'BACAXÁ', 'LINHA 23 ÁGUA BRANCA', 'TERMINAL BACAXÁ, CAIXA D´ÁGUA, ÁGUA BRANCA, MANGUEIRAS, CAJUEIRO E VILATUR.', False, False),
    ('11:55', 'VILATUR', 'BACAXÁ', 'LINHA 23 ÁGUA BRANCA', 'TERMINAL BACAXÁ, CAIXA D´ÁGUA, ÁGUA BRANCA, MANGUEIRAS, CAJUEIRO E VILATUR.', False, False),
    ('12:35', 'VILATUR', 'BACAXÁ', 'LINHA 23 ÁGUA BRANCA', 'TERMINAL BACAXÁ, CAIXA D´ÁGUA, ÁGUA BRANCA, MANGUEIRAS, CAJUEIRO E VILATUR.', False, False),
    ('12:55', 'VILATUR', 'BACAXÁ', 'LINHA 42 ROD. AMARAL PEIXOTO', 'ROD. AMARAL PEIXOTO PRÓXIMO AO PONTO MONTES BRANCOS, BONSUCESSO E VILATUR', False, False),
    ('13:15', 'VILATUR', 'BACAXÁ', 'LINHA 23 ÁGUA BRANCA', 'TERMINAL BACAXÁ, CAIXA D´ÁGUA, ÁGUA BRANCA, MANGUEIRAS, CAJUEIRO E VILATUR.', False, False),
    ('13:55', 'VILATUR', 'BACAXÁ', 'LINHA 23 ÁGUA BRANCA', 'TERMINAL BACAXÁ, CAIXA D´ÁGUA, ÁGUA BRANCA, MANGUEIRAS, CAJUEIRO E VILATUR.', False, False),
    ('14:35', 'VILATUR', 'BACAXÁ', 'LINHA 23 ÁGUA BRANCA', 'TERMINAL BACAXÁ, CAIXA D´ÁGUA, ÁGUA BRANCA, MANGUEIRAS, CAJUEIRO E VILATUR.', False, False),
    ('15:15', 'VILATUR', 'BACAXÁ', 'LINHA 23 ÁGUA BRANCA', 'TERMINAL BACAXÁ, CAIXA D´ÁGUA, ÁGUA BRANCA, MANGUEIRAS, CAJUEIRO E VILATUR.', False, False),
    ('15:55', 'VILATUR', 'BACAXÁ', 'LINHA 23 ÁGUA BRANCA', 'TERMINAL BACAXÁ, CAIXA D´ÁGUA, ÁGUA BRANCA, MANGUEIRAS, CAJUEIRO E VILATUR.', False, False),
    ('16:35', 'VILATUR', 'BACAXÁ', 'LINHA 23 ÁGUA BRANCA', 'TERMINAL BACAXÁ, CAIXA D´ÁGUA, ÁGUA BRANCA, MANGUEIRAS, CAJUEIRO E VILATUR.', False, False),
    ('17:15', 'VILATUR', 'BACAXÁ', 'LINHA 23 ÁGUA BRANCA', 'TERMINAL BACAXÁ, CAIXA D´ÁGUA, ÁGUA BRANCA, MANGUEIRAS, CAJUEIRO E VILATUR.', False, False),
    ('17:35', 'VILATUR', 'BACAXÁ', 'LINHA 42 ROD. AMARAL PEIXOTO', 'ROD. AMARAL PEIXOTO PRÓXIMO AO PONTO MONTES BRANCOS, BONSUCESSO E VILATUR', False, False),
    ('17:55', 'VILATUR', 'BACAXÁ', 'LINHA 23 ÁGUA BRANCA', 'TERMINAL BACAXÁ, CAIXA D´ÁGUA, ÁGUA BRANCA, MANGUEIRAS, CAJUEIRO E VILATUR.', False, False),
    ('18:35', 'VILATUR', 'BACAXÁ', 'LINHA 23 ÁGUA BRANCA', 'TERMINAL BACAXÁ, CAIXA D´ÁGUA, ÁGUA BRANCA, MANGUEIRAS, CAJUEIRO E VILATUR.', False, False),
    ('18:55', 'VILATUR', 'BACAXÁ', 'LINHA 42 ROD. AMARAL PEIXOTO', 'ROD. AMARAL PEIXOTO PRÓXIMO AO PONTO MONTES BRANCOS, BONSUCESSO E VILATUR', False, False),
    ('19:35', 'VILATUR', 'BACAXÁ', 'LINHA 23 ÁGUA BRANCA', 'TERMINAL BACAXÁ, CAIXA D´ÁGUA, ÁGUA BRANCA, MANGUEIRAS, CAJUEIRO E VILATUR.', False, False),
    ('20:55', 'VILATUR', 'BACAXÁ', 'LINHA 23 ÁGUA BRANCA', 'TERMINAL BACAXÁ, CAIXA D´ÁGUA, ÁGUA BRANCA, MANGUEIRAS, CAJUEIRO E VILATUR.', False, False),
    ('22:00', 'VILATUR', 'BACAXÁ', 'LINHA 23 ÁGUA BRANCA', 'TERMINAL BACAXÁ, CAIXA D´ÁGUA, ÁGUA BRANCA, MANGUEIRAS, CAJUEIRO E VILATUR.', False, False),
    ('05:40', 'BACAXÁ', 'VILATUR', 'LINHA 23 ÁGUA BRANCA', 'TERMINAL BACAXÁ, CAIXA D´ÁGUA, ÁGUA BRANCA, MANGUEIRAS, CAJUEIRO E VILATUR.', True, False),
    ('06:00', 'BACAXÁ', 'VILATUR', 'LINHA 23 ÁGUA BRANCA', 'TERMINAL BACAXÁ, CAIXA D´ÁGUA, ÁGUA BRANCA, MANGUEIRAS, CAJUEIRO E VILATUR.', True, False),
    ('06:40', 'BACAXÁ', 'VILATUR', 'LINHA 23 ÁGUA BRANCA', 'TERMINAL BACAXÁ, CAIXA D´ÁGUA, ÁGUA BRANCA, MANGUEIRAS, CAJUEIRO E VILATUR.', True, False),
    ('07:00', 'BACAXÁ', 'VILATUR', 'LINHA 42 ROD. AMARAL PEIXOTO', 'ROD. AMARAL PEIXOTO PRÓXIMO AO PONTO MONTES BRANCOS, BONSUCESSO E VILATUR', True, False),
    ('07:20', 'BACAXÁ', 'VILATUR', 'LINHA 23 ÁGUA BRANCA', 'TERMINAL BACAXÁ, CAIXA D´ÁGUA, ÁGUA BRANCA, MANGUEIRAS, CAJUEIRO E VILATUR.', True, False),
    ('08:00', 'BACAXÁ', 'VILATUR', 'LINHA 23 ÁGUA BRANCA', 'TERMINAL BACAXÁ, CAIXA D´ÁGUA, ÁGUA BRANCA, MANGUEIRAS, CAJUEIRO E VILATUR.', True, False),
    ('08:40', 'BACAXÁ', 'VILATUR', 'LINHA 23 ÁGUA BRANCA', 'TERMINAL BACAXÁ, CAIXA D´ÁGUA, ÁGUA BRANCA, MANGUEIRAS, CAJUEIRO E VILATUR.', True, False),
    ('09:20', 'BACAXÁ', 'VILATUR', 'LINHA 23 ÁGUA BRANCA', 'TERMINAL BACAXÁ, CAIXA D´ÁGUA, ÁGUA BRANCA, MANGUEIRAS, CAJUEIRO E VILATUR.', True, False),
    ('10:00', 'BACAXÁ', 'VILATUR', 'LINHA 23 ÁGUA BRANCA', 'TERMINAL BACAXÁ, CAIXA D´ÁGUA, ÁGUA BRANCA, MANGUEIRAS, CAJUEIRO E VILATUR.', True, False),
    ('10:40', 'BACAXÁ', 'VILATUR', 'LINHA 23 ÁGUA BRANCA', 'TERMINAL BACAXÁ, CAIXA D´ÁGUA, ÁGUA BRANCA, MANGUEIRAS, CAJUEIRO E VILATUR.', True, False),
    ('11:20', 'BACAXÁ', 'VILATUR', 'LINHA 23 ÁGUA BRANCA', 'TERMINAL BACAXÁ, CAIXA D´ÁGUA, ÁGUA BRANCA, MANGUEIRAS, CAJUEIRO E VILATUR.', True, False),
    ('12:00', 'BACAXÁ', 'VILATUR', 'LINHA 23 ÁGUA BRANCA', 'TERMINAL BACAXÁ, CAIXA D´ÁGUA, ÁGUA BRANCA, MANGUEIRAS, CAJUEIRO E VILATUR.', True, False),
    ('12:40', 'BACAXÁ', 'VILATUR', 'LINHA 42 ROD. AMARAL PEIXOTO', 'ROD. AMARAL PEIXOTO PRÓXIMO AO PONTO MONTES BRANCOS, BONSUCESSO E VILATUR', True, False),
    ('13:20', 'BACAXÁ', 'VILATUR', 'LINHA 23 ÁGUA BRANCA', 'TERMINAL BACAXÁ, CAIXA D´ÁGUA, ÁGUA BRANCA, MANGUEIRAS, CAJUEIRO E VILATUR.', True, False),
    ('14:40', 'BACAXÁ', 'VILATUR', 'LINHA 23 ÁGUA BRANCA', 'TERMINAL BACAXÁ, CAIXA D´ÁGUA, ÁGUA BRANCA, MANGUEIRAS, CAJUEIRO E VILATUR.', True, False),
    ('16:00', 'BACAXÁ', 'VILATUR', 'LINHA 23 ÁGUA BRANCA', 'TERMINAL BACAXÁ, CAIXA D´ÁGUA, ÁGUA BRANCA, MANGUEIRAS, CAJUEIRO E VILATUR.', True, False),
    ('16:40', 'BACAXÁ', 'VILATUR', 'LINHA 42 ROD. AMARAL PEIXOTO', 'ROD. AMARAL PEIXOTO PRÓXIMO AO PONTO MONTES BRANCOS, BONSUCESSO E VILATUR', True, False),
    ('17:20', 'BACAXÁ', 'VILATUR', 'LINHA 23 ÁGUA BRANCA', 'TERMINAL BACAXÁ, CAIXA D´ÁGUA, ÁGUA BRANCA, MANGUEIRAS, CAJUEIRO E VILATUR.', True, False),
    ('19:00', 'BACAXÁ', 'VILATUR', 'LINHA 23 ÁGUA BRANCA', 'TERMINAL BACAXÁ, CAIXA D´ÁGUA, ÁGUA BRANCA, MANGUEIRAS, CAJUEIRO E VILATUR.', True, False),
    ('20:20', 'BACAXÁ', 'VILATUR', 'LINHA 23 ÁGUA BRANCA', 'TERMINAL BACAXÁ, CAIXA D´ÁGUA, ÁGUA BRANCA, MANGUEIRAS, CAJUEIRO E VILATUR.', True, False),
    ('21:30', 'BACAXÁ', 'VILATUR', 'LINHA 23 ÁGUA BRANCA', 'TERMINAL BACAXÁ, CAIXA D´ÁGUA, ÁGUA BRANCA, MANGUEIRAS, CAJUEIRO E VILATUR.', True, False),
    ('06:10', 'VILATUR', 'BACAXÁ', 'LINHA 23 ÁGUA BRANCA', 'TERMINAL VILATUR, ÁGUA BRANCA, MANGUEIRAS, CAJUEIRO, TERMINAL BACAXÁ', True, False),
    ('06:40', 'VILATUR', 'BACAXÁ', 'LINHA 23 ÁGUA BRANCA', 'TERMINAL VILATUR, ÁGUA BRANCA, MANGUEIRAS, CAJUEIRO, TERMINAL BACAXÁ', True, False),
    ('07:15', 'VILATUR', 'BACAXÁ', 'LINHA 23 ÁGUA BRANCA', 'TERMINAL VILATUR, ÁGUA BRANCA, MANGUEIRAS, CAJUEIRO, TERMINAL BACAXÁ', True, False),
    ('07:35', 'VILATUR', 'BACAXÁ', 'LINHA 42 ROD. AMARAL PEIXOTO', 'TERMINAL VILATUR, ROD. AMARAL PEIXOTO PRÓXIMO AO PONTO MONTES BRANCOS, BONSUCESSO E TERMINAL BACAXÁ', True, False),
    ('07:55', 'VILATUR', 'BACAXÁ', 'LINHA 23 ÁGUA BRANCA', 'TERMINAL VILATUR, ÁGUA BRANCA, MANGUEIRAS, CAJUEIRO, TERMINAL BACAXÁ', True, False),
    ('08:35', 'VILATUR', 'BACAXÁ', 'LINHA 23 ÁGUA BRANCA', 'TERMINAL VILATUR, ÁGUA BRANCA, MANGUEIRAS, CAJUEIRO, TERMINAL BACAXÁ', True, False),
    ('09:15', 'VILATUR', 'BACAXÁ', 'LINHA 23 ÁGUA BRANCA', 'TERMINAL VILATUR, ÁGUA BRANCA, MANGUEIRAS, CAJUEIRO, TERMINAL BACAXÁ', True, False),
    ('09:55', 'VILATUR', 'BACAXÁ', 'LINHA 23 ÁGUA BRANCA', 'TERMINAL VILATUR, ÁGUA BRANCA, MANGUEIRAS, CAJUEIRO, TERMINAL BACAXÁ', True, False),
    ('10:35', 'VILATUR', 'BACAXÁ', 'LINHA 23 ÁGUA BRANCA', 'TERMINAL VILATUR, ÁGUA BRANCA, MANGUEIRAS, CAJUEIRO, TERMINAL BACAXÁ', True, False),
    ('11:15', 'VILATUR', 'BACAXÁ', 'LINHA 23 ÁGUA BRANCA', 'TERMINAL VILATUR, ÁGUA BRANCA, MANGUEIRAS, CAJUEIRO, TERMINAL BACAXÁ', True, False),
    ('11:55', 'VILATUR', 'BACAXÁ', 'LINHA 23 ÁGUA BRANCA', 'TERMINAL VILATUR, ÁGUA BRANCA, MANGUEIRAS, CAJUEIRO, TERMINAL BACAXÁ', True, False),
    ('12:35', 'VILATUR', 'BACAXÁ', 'LINHA 23 ÁGUA BRANCA', 'TERMINAL VILATUR, ÁGUA BRANCA, MANGUEIRAS, CAJUEIRO, TERMINAL BACAXÁ', True, False),
    ('13:15', 'VILATUR', 'BACAXÁ', 'LINHA 42 ROD. AMARAL PEIXOTO', 'TERMINAL VILATUR, ROD. AMARAL PEIXOTO PRÓXIMO AO PONTO MONTES BRANCOS, BONSUCESSO E TERMINAL BACAXÁ', True, False),
    ('13:55', 'VILATUR', 'BACAXÁ', 'LINHA 23 ÁGUA BRANCA', 'TERMINAL VILATUR, ÁGUA BRANCA, MANGUEIRAS, CAJUEIRO, TERMINAL BACAXÁ', True, False),
    ('15:15', 'VILATUR', 'BACAXÁ', 'LINHA 23 ÁGUA BRANCA', 'TERMINAL VILATUR, ÁGUA BRANCA, MANGUEIRAS, CAJUEIRO, TERMINAL BACAXÁ', True, False),
    ('16:35', 'VILATUR', 'BACAXÁ', 'LINHA 23 ÁGUA BRANCA', 'TERMINAL VILATUR, ÁGUA BRANCA, MANGUEIRAS, CAJUEIRO, TERMINAL BACAXÁ', True, False),
    ('17:15', 'VILATUR', 'BACAXÁ', 'LINHA 42 ROD. AMARAL PEIXOTO', 'TERMINAL VILATUR, ROD. AMARAL PEIXOTO PRÓXIMO AO PONTO MONTES BRANCOS, BONSUCESSO E TERMINAL BACAXÁ', True, False),
    ('17:55', 'VILATUR', 'BACAXÁ', 'LINHA 23 ÁGUA BRANCA', 'TERMINAL VILATUR, ÁGUA BRANCA, MANGUEIRAS, CAJUEIRO, TERMINAL BACAXÁ', True, False),
    ('19:35', 'VILATUR', 'BACAXÁ', 'LINHA 23 ÁGUA BRANCA', 'TERMINAL VILATUR, ÁGUA BRANCA, MANGUEIRAS, CAJUEIRO, TERMINAL BACAXÁ', True, False),
    ('20:55', 'VILATUR', 'BACAXÁ', 'LINHA 23 ÁGUA BRANCA', 'TERMINAL VILATUR, ÁGUA BRANCA, MANGUEIRAS, CAJUEIRO, TERMINAL BACAXÁ', True, False),
    ('22:00', 'VILATUR', 'BACAXÁ', 'LINHA 23 ÁGUA BRANCA', 'TERMINAL VILATUR, ÁGUA BRANCA, MANGUEIRAS, CAJUEIRO, TERMINAL BACAXÁ', True, False),
    ('06:00', 'BACAXÁ', 'VILATUR', 'LINHA 23 ÁGUA BRANCA',
     'TERMINAL BACAXÁ, CAIXA D´ÁGUA, ÁGUA BRANCA, MANGUEIRAS, CAJUEIRO E VILATUR.', False, True),
    ('07:20', 'BACAXÁ', 'VILATUR', 'LINHA 23 ÁGUA BRANCA',
     'TERMINAL BACAXÁ, CAIXA D´ÁGUA, ÁGUA BRANCA, MANGUEIRAS, CAJUEIRO E VILATUR.', False, True),
    ('08:40', 'BACAXÁ', 'VILATUR', 'LINHA 23 ÁGUA BRANCA',
     'TERMINAL BACAXÁ, CAIXA D´ÁGUA, ÁGUA BRANCA, MANGUEIRAS, CAJUEIRO E VILATUR.', False, True),
    ('10:00', 'BACAXÁ', 'VILATUR', 'LINHA 23 ÁGUA BRANCA',
     'TERMINAL BACAXÁ, CAIXA D´ÁGUA, ÁGUA BRANCA, MANGUEIRAS, CAJUEIRO E VILATUR.', False, True),
    ('11:20', 'BACAXÁ', 'VILATUR', 'LINHA 23 ÁGUA BRANCA',
     'TERMINAL BACAXÁ, CAIXA D´ÁGUA, ÁGUA BRANCA, MANGUEIRAS, CAJUEIRO E VILATUR.', False, True),
    ('12:40', 'BACAXÁ', 'VILATUR', 'LINHA 23 ÁGUA BRANCA',
     'TERMINAL BACAXÁ, CAIXA D´ÁGUA, ÁGUA BRANCA, MANGUEIRAS, CAJUEIRO E VILATUR.', False, True),
    ('14:00', 'BACAXÁ', 'VILATUR', 'LINHA 23 ÁGUA BRANCA',
     'TERMINAL BACAXÁ, CAIXA D´ÁGUA, ÁGUA BRANCA, MANGUEIRAS, CAJUEIRO E VILATUR.', False, True),
    ('15:20', 'BACAXÁ', 'VILATUR', 'LINHA 23 ÁGUA BRANCA',
     'TERMINAL BACAXÁ, CAIXA D´ÁGUA, ÁGUA BRANCA, MANGUEIRAS, CAJUEIRO E VILATUR.', False, True),
    ('16:40', 'BACAXÁ', 'VILATUR', 'LINHA 23 ÁGUA BRANCA',
     'TERMINAL BACAXÁ, CAIXA D´ÁGUA, ÁGUA BRANCA, MANGUEIRAS, CAJUEIRO E VILATUR.', False, True),
    ('18:00', 'BACAXÁ', 'VILATUR', 'LINHA 23 ÁGUA BRANCA',
     'TERMINAL BACAXÁ, CAIXA D´ÁGUA, ÁGUA BRANCA, MANGUEIRAS, CAJUEIRO E VILATUR.', False, True),
    ('19:00', 'BACAXÁ', 'VILATUR', 'LINHA 23 ÁGUA BRANCA',
     'TERMINAL BACAXÁ, CAIXA D´ÁGUA, ÁGUA BRANCA, MANGUEIRAS, CAJUEIRO E VILATUR.', False, True),
    ('20:20', 'BACAXÁ', 'VILATUR', 'LINHA 23 ÁGUA BRANCA',
     'TERMINAL BACAXÁ, CAIXA D´ÁGUA, ÁGUA BRANCA, MANGUEIRAS, CAJUEIRO E VILATUR.', False, True),
    ('21:30', 'BACAXÁ', 'VILATUR', 'LINHA 23 ÁGUA BRANCA',
     'TERMINAL BACAXÁ, CAIXA D´ÁGUA, ÁGUA BRANCA, MANGUEIRAS, CAJUEIRO E VILATUR.', False, True),
    ('06:40', 'VILATUR', 'BACAXÁ', 'LINHA 23 ÁGUA BRANCA', 'TERMINAL VILATUR, CAIXA D´ÁGUA, ÁGUA BRANCA, MANGUEIRAS, CAJUEIRO E BACAXÁ.', False, True),
    ('07:55', 'VILATUR', 'BACAXÁ', 'LINHA 23 ÁGUA BRANCA', 'TERMINAL VILATUR, CAIXA D´ÁGUA, ÁGUA BRANCA, MANGUEIRAS, CAJUEIRO E BACAXÁ.', False, True),
    ('09:15', 'VILATUR', 'BACAXÁ', 'LINHA 23 ÁGUA BRANCA', 'TERMINAL VILATUR, CAIXA D´ÁGUA, ÁGUA BRANCA, MANGUEIRAS, CAJUEIRO E BACAXÁ.', False, True),
    ('10:35', 'VILATUR', 'BACAXÁ', 'LINHA 23 ÁGUA BRANCA', 'TERMINAL VILATUR, CAIXA D´ÁGUA, ÁGUA BRANCA, MANGUEIRAS, CAJUEIRO E BACAXÁ.', False, True),
    ('11:55', 'VILATUR', 'BACAXÁ', 'LINHA 23 ÁGUA BRANCA', 'TERMINAL VILATUR, CAIXA D´ÁGUA, ÁGUA BRANCA, MANGUEIRAS, CAJUEIRO E BACAXÁ.', False, True),
    ('13:15', 'VILATUR', 'BACAXÁ', 'LINHA 23 ÁGUA BRANCA', 'TERMINAL VILATUR, CAIXA D´ÁGUA, ÁGUA BRANCA, MANGUEIRAS, CAJUEIRO E BACAXÁ.', False, True),
    ('14:35', 'VILATUR', 'BACAXÁ', 'LINHA 23 ÁGUA BRANCA', 'TERMINAL VILATUR, CAIXA D´ÁGUA, ÁGUA BRANCA, MANGUEIRAS, CAJUEIRO E BACAXÁ.', False, True),
    ('15:55', 'VILATUR', 'BACAXÁ', 'LINHA 23 ÁGUA BRANCA', 'TERMINAL VILATUR, CAIXA D´ÁGUA, ÁGUA BRANCA, MANGUEIRAS, CAJUEIRO E BACAXÁ.', False, True),
    ('17:15', 'VILATUR', 'BACAXÁ', 'LINHA 23 ÁGUA BRANCA', 'TERMINAL VILATUR, CAIXA D´ÁGUA, ÁGUA BRANCA, MANGUEIRAS, CAJUEIRO E BACAXÁ.', False, True),
    ('18:35', 'VILATUR', 'BACAXÁ', 'LINHA 23 ÁGUA BRANCA', 'TERMINAL VILATUR, CAIXA D´ÁGUA, ÁGUA BRANCA, MANGUEIRAS, CAJUEIRO E BACAXÁ.', False, True),
    ('19:35', 'VILATUR', 'BACAXÁ', 'LINHA 23 ÁGUA BRANCA', 'TERMINAL VILATUR, CAIXA D´ÁGUA, ÁGUA BRANCA, MANGUEIRAS, CAJUEIRO E BACAXÁ.', False, True),
    ('20:55', 'VILATUR', 'BACAXÁ', 'LINHA 23 ÁGUA BRANCA', 'TERMINAL VILATUR, CAIXA D´ÁGUA, ÁGUA BRANCA, MANGUEIRAS, CAJUEIRO E BACAXÁ.', False, True),
    ('22:00', 'VILATUR', 'BACAXÁ', 'LINHA 23 ÁGUA BRANCA', 'TERMINAL VILATUR, CAIXA D´ÁGUA, ÁGUA BRANCA, MANGUEIRAS, CAJUEIRO E BACAXÁ.', False, True),
]

cursor.executemany(lines_sql, lines)

cursor.execute('select * from saquabus.bus_lines')
print(' -------------  Lines:  -------------')
for jogo in cursor.fetchall():
    print(jogo[1])

# commitando se não nada tem efeito
conn.commit()

cursor.close()
conn.close()